#开发环境

#tomcat
server:
  port: 8888

#swagger 开启
swagger:
  enable: true

#druid 数据源
sprin:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accordmall?useSSL=false&useUnicode=true&characherEncoding=utf8&serverTimezone=PRC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #druid
    initialSize: 10 #初始化连接数
    maxActive: 100 #最大连接
    maxWait: 60000 #最大等待时间
    timeBetweenEvictionRunsMillis: 60000 #检查空闲连接的时间
    # druid数据源 配置监控 , stat:监控统计 , lo4j: 日志记录,wall：防御SQL注入
    filters: stat,wall,log4j
    maxPoolPreparedStatemetPerConnectionSeze: 20
    useGlobalDataSourceStat: true
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#log4j
#logging:
#  level: debug
#  cn.accordmall.mapper: debug


#mybaties-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

